SLG/Models/SaleOrder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SLG.Models;

public partial class Sale_Order
{
    [Display(Name = "ID")]
    public int sale_id { get; set; }
    [Display(Name = "Customer")]
    public int customer_id { get; set; }
    [Display(Name = "Document Name"),NotMapped]
    public string name { get; set; } = null!;
    [Display(Name = "Total Amount")]
    public decimal total_amount { get; set; }
    
    [Display(Name = "Date Created")]
    public DateTime? date_created { get; set; }
    [Display(Name = "Status")]
    public string? state { get; set; }


    public virtual ICollection<Sale_Order_Detail> Sale_Order_Details { get; set; } = new List<Sale_Order_Detail>();

    public virtual Customer customer { get; set; } = null!;
    
}

SLG/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SLG.Data;
using SLG.Models;

namespace SLG.Controllers
{
    public class ProductsController : Controller
    {
        private readonly SLGC _context;

        public ProductsController(SLGC context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            var fYPContext = _context.Products.Include(p => p.category);
            return View(await fYPContext.ToListAsync());
        }
        public IActionResult GetProducts()
        {
            var products = _context.Products.Select(p => new SelectListItem
            {
                Value = p.product_id.ToString(),
                Text = p.name
            }).ToList();

            return Json(products);
        }
        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.category)
                .FirstOrDefaultAsync(m => m.product_id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["category_id"] = new SelectList(_context.Categories, "category_id", "category_name");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("product_id,name,description,quantity,unit_price,category_id,reorder_level,discontinued")] Product product)
        {
            //if (ModelState.IsValid)
            //{
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            //}
            ViewData["category_id"] = new SelectList(_context.Categories, "category_id", "category_name", product.category_id);
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["category_id"] = new SelectList(_context.Categories, "category_id", "category_name", product.category_id);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("product_id,name,description,quantity,unit_price,category_id,reorder_level,discontinued")] Product product)
        {
            if (id != product.product_id)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            //{
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.product_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            //}
            ViewData["category_id"] = new SelectList(_context.Categories, "category_id", "category_name", product.category_id);
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.category)
                .FirstOrDefaultAsync(m => m.product_id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Products == null)
            {
                return Problem("Entity set 'FYPContext.Products'  is null.");
            }
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                _context.Products.Remove(product);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
          return (_context.Products?.Any(e => e.product_id == id)).GetValueOrDefault();
        }
    }
}

SLG/Controllers/Sale_OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SLG.Data;
using SLG.Models;
using SLG.ViewModels;
using System;

namespace SLG.Controllers
{
    public class Sale_OrderController : Controller
    {
        private int count = 0;

        private readonly SLGC _context;


        public Sale_OrderController(SLGC context)
        {
            _context = context;
            
        }

        // GET: Sale_Order
        public async Task<IActionResult> Index()
        {
            var fYPContext = _context.Sale_Orders.Include(s => s.customer);
            return View(await fYPContext.ToListAsync());
        }

        // GET: Sale_Order/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            //var viewModel = new SalesViewModel
            //{
            //    SaleOrder = new Sale_Order(),
            //    SaleItems = new List<Sale_Order_Detail>(),
            //};
            //if (id == null || _context.Sale_Orders == null)
            //{
            //    return NotFound();
            //}

            //var sale_Order = await _context.Sale_Orders
            //    .Include(s => s.customer)
            //    .Include(s => s.payment_methodNavigation)
            //    .FirstOrDefaultAsync(m => m.sale_id == id);
            //if (sale_Order == null)
            //{
            //    return NotFound();
            //}

            //return View(viewModel);

            if (id == null)
            {
                return NotFound();
            }

            var sale_Order = await _context.Sale_Orders
                .Include(s => s.customer)
                
                .FirstOrDefaultAsync(m => m.sale_id == id);

            if (sale_Order == null)
            {
                return NotFound();
            }

            var viewModel = new SalesViewModel
            {
                SaleOrder = sale_Order,
                SaleItems = await _context.Sale_Order_Details
                .Include(d => d.product)
            .Where(d => d.sale_id == id)
            .ToListAsync()
            };

            return View(viewModel);
        }

        // GET: Sale_Order/Create

        public IActionResult Create()
        {
            ViewData["customer_id"] = new SelectList(_context.Customers, "customer_id", "customer_name");
            
            ViewData["product_id"] = new SelectList(_context.Products, "product_id", "name");
            var viewModel = new SalesViewModel
            {
                SaleOrder = new Sale_Order(),
                SaleItems = new List<Sale_Order_Detail>(),
            };

            return View(viewModel);
        }


        // POST: Sale_Order/Create
        //public async Task<IActionResult> Create([Bind("sale_id,customer_id,name,total_amount,payment_method,date_created,state")] Sale_Order sale_Order)
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SalesViewModel viewModel)
        {
            // Save the sale order header to the database
            var count = _context.Sale_Order_Details.Count();
            //viewModel.SaleOrder.name = "S" + (count + 1).ToString();
            _context.Sale_Orders.Add(viewModel.SaleOrder);
            _context.SaveChanges();

            // Associate the line items with the sale order
            if(viewModel.SaleItems is not null) { 
            foreach (var item in viewModel.SaleItems)
            {
                var lineItem = new Sale_Order_Detail
                {
                    sale_id = viewModel.SaleOrder.sale_id,
                    product_id = item.product_id,
                    quantity = item.quantity,
                    price = item.price
                };
                //if (lineItem.quantity < lineItem.product.quantity)
                //{
                _context.Sale_Order_Details.Add(lineItem);
                _context.SaveChanges();
                //}
            }
            }

            // Redirect to a success page or take appropriate action
            return RedirectToAction("Index");
            //}
            return View(viewModel);
        }

        // GET: Sale_Order/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            //if (id == null || _context.Sale_Orders == null)
            //{
            //    return NotFound();
            //}

            //var sale_Order = await _context.Sale_Orders.FindAsync(id);
            //if (sale_Order == null)
            //{
            //    return NotFound();
            //}

            //ViewData["customer_id"] = new SelectList(_context.Customers, "customer_id", "customer_id", sale_Order.customer_id);
            //ViewData["payment_method"] = new SelectList(_context.Payments, "id", "method_name", sale_Order.payment_method);
            //return View(sale_Order);

            if (id == null || _context.Sale_Orders == null)
            {
                return NotFound();
            }

            var sale_Order = await _context.Sale_Orders
                            .Include(s => s.customer)
                            .FirstOrDefaultAsync(m => m.sale_id == id);
            if (sale_Order == null)
            {
                return NotFound();
            }

            var viewModel = new SalesViewModel
            {
                SaleOrder = sale_Order,
                SaleItems = await _context.Sale_Order_Details
                .Include(d => d.product)
            .Where(d => d.sale_id == id)
            .ToListAsync()
            };
            ViewData["product_id"] = new SelectList(_context.Products, "product_id", "name");

            ViewData["customer_id"] = new SelectList(_context.Customers, "customer_id", "customer_id", sale_Order.customer_id);
            
            return View(viewModel);

        }

        // POST: Sale_Order/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("sale_id,customer_id,name,total_amount,payment_method,date_created,state")] Sale_Order sale_Order)
        public async Task<IActionResult> Edit(int id, SalesViewModel viewModel)
        {
            if (id != viewModel.SaleOrder.sale_id)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            //{
            try
            {
                _context.Update(viewModel.SaleOrder);
                await _context.SaveChangesAsync();
                _context.Update(viewModel.SaleItems);
                await _context.SaveChangesAsync();

            }
            catch (DbUpdateConcurrencyException)
            {
                if (!Sale_OrderExists(viewModel.SaleOrder.sale_id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
            //}
            ViewData["customer_id"] = new SelectList(_context.Customers, "customer_id", "customer_id", viewModel.SaleOrder.customer_id);
            
            return View(viewModel);
        }


        // GET: Sale_Order/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Sale_Orders == null)
            {
                return NotFound();
            }

            var sale_Order = await _context.Sale_Orders
                .Include(s => s.customer)
               
                .FirstOrDefaultAsync(m => m.sale_id == id);
            if (sale_Order == null)
            {
                return NotFound();
            }

            return View(sale_Order);
        }

        // POST: Sale_Order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Sale_Orders == null)
            {
                return Problem("Entity set 'FYPContext.Sale_Orders'  is null.");
            }
            var sale_Order = await _context.Sale_Orders.FindAsync(id);
            if (sale_Order != null)
            {
                _context.Sale_Orders.Remove(sale_Order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Sale_OrderExists(int id)
        {
            return (_context.Sale_Orders?.Any(e => e.sale_id == id)).GetValueOrDefault();
        }


        // POST: SaleOrders/ConfirmSaleOrder/5
        [HttpGet]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmSaleOrder(int id)
        {
            // Find the sale order by ID
            var saleOrder = await _context.Sale_Orders
                .Include(so => so.Sale_Order_Details)
                .FirstOrDefaultAsync(so => so.sale_id == id);

            if (saleOrder == null)
            {
                return NotFound();
            }

            // Check if the sale order is already confirmed
            if (saleOrder.state == "Sale Order")
            {
                //return BadRequest("Sale order is already confirmed.");
                TempData["SalePopupMessage"] = "Sale order is already confirmed.";
                return RedirectToAction(nameof(Index));
            }

            // Update the state to "Sale"
            saleOrder.state = "Sale Order";
            _context.Update(saleOrder);
            await _context.SaveChangesAsync();

SLG/Views/Sale_Order/Create.cshtml
@using Microsoft.EntityFrameworkCore.Metadata.Internal;
@using SLG.ViewModels
@model SalesViewModel

@using (Html.BeginForm("Create", "Sale_Order", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div>
        <h4>Sale Order Information</h4>
        <div class="row"></div>
        <div class="form-group">
            <label asp-for="SaleOrder.name" class="control-label"></label>
            <span>New</span>
            @* <input asp-for="SaleOrder.name" value="New" class="form-control" readonly/> *@
            @* <span asp-validation-for="SaleOrder.name" class="text-danger"></span> *@
        </div>

        <div class="form-group">
            <label asp-for="SaleOrder.customer_id" class="control-label"></label>
            @*<input asp-for="SaleOrder.customer_id" class="form-control" />*@
            @Html.DropDownList("SaleOrder.customer_id", (SelectList)ViewData["customer_id"], "Select a customer", new { @class = "form-control" })
            <span asp-validation-for="SaleOrder.customer_id" class="text-danger"></span>
        </div>
        
    </div>

    <div>
        <div class="row">
            <div class="col-9">
                <h4>Line Items</h4>
            </div>
            <div class="col-3 text-right">
                <button type="button" id="addLineItem" class="btn btn-primary">Add Line Item</button>
            </div>
        </div>
        <br>

        <table class="table table-bordered border-dark">
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="lineItemsBody">
                @for (int i = 0; i < Model.SaleItems.Count; i++)
                {
                    <tr>
                        <td>
                            @Html.DropDownListFor(model => model.SaleItems[i].product_id, (SelectList)ViewData["product_id"], "Select a Product", new { @class = "form-control" })
                            <span asp-validation-for="SaleItems[i].product_id" class="text-danger"></span>
                        </td>
                        <td>
                            <input asp-for="SaleItems[i].quantity" class="form-control" />
                            <span asp-validation-for="SaleItems[i].quantity" class="text-danger"></span>
                        </td>
                        <td>
                            <input asp-for="SaleItems[i].price" class="form-control" />
                            <span asp-validation-for="SaleItems[i].price" class="text-danger"></span>
                        </td>
                        <td>
                            <button type="button" class="btn btn-danger removeLineItem">Remove</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
}

@section Scripts {
    <script>
        $(document).ready(function () {
            var index = @Model.SaleItems.Count;

            $('#addLineItem').click(function () {
                var newRow = '<tr>' +
                    '<td><select class="form-select" name="SaleItems[' + index + '].product_id" required><option value="">Select a Product</option></select></td>' +
                    '<td><input class="form-control" name="SaleItems[' + index + '].quantity" required/></td>' +
                    '<td><input class="form-control" name="SaleItems[' + index + '].price" required/></td>' +
                    '<td><button type="button" class="btn btn-danger removeLineItem">Remove</button></td>' +
                    '</tr>';

                $('#lineItemsBody').append(newRow);

                var select = $('select[name="SaleItems[' + index + '].product_id"]');
                $.get('@Url.Action("GetProducts", "Products")', function (data) {
                    select.empty();
                    $.each(data, function (index, item) {
                        select.append($('<option></option>').val(item.value).text(item.text));
                    });
                });

                $('input[name="SaleItems[' + index + '].quantity"]').on('keyup blur', function () {
                    var quantityInput = $(this);
                    var quantityValue = parseFloat(quantityInput.val());
                    if (quantityValue < 0) {
                        quantityInput.val(0); // Set value to 0 if negative
                        alert("Quantity cannot be negative."); // Or display a custom error message
                    }
                });

                $('input[name="SaleItems[' + index + '].price"]').on('keyup blur', function () {
                    var priceInput = $(this);
                    var priceValue = parseFloat(priceInput.val());
                    if (priceValue < 0) {
                        priceInput.val(0); // Set value to 0 if negative
                        alert("Price cannot be negative."); // Or display a custom error message
                    }
                });

                index++;
            });

            $(document).on('click', '.removeLineItem', function () {
                $(this).closest('tr').remove();
            });
        });
    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

SLG/Views/Sale_Order/Delete.cshtml
@model Sale_Order

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sale_Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.total_amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.total_amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.date_created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.date_created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.state)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.state)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.customer.customer_id)
        </dd>
        
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="sale_id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SLG/Views/Sale_Order/Edit.cshtml
@*@model Sale_Order*@
@model SLG.ViewModels.SalesViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Sale_Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SaleOrder.sale_id" />
            <div class="form-group">
                <label asp-for="SaleOrder.customer_id" class="control-label"></label>
                <select asp-for="SaleOrder.customer_id" class="form-control" asp-items="ViewBag.customer_id"></select>
                <span asp-validation-for="SaleOrder.customer_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SaleOrder.name" class="control-label"></label>
                <input asp-for="SaleOrder.name" class="form-control" />
                <span asp-validation-for="SaleOrder.name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SaleOrder.total_amount" class="control-label"></label>
                <input asp-for="SaleOrder.total_amount" class="form-control" />
                <span asp-validation-for="SaleOrder.total_amount" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="SaleOrder.payment_method" class="control-label"></label>
                <select asp-for="SaleOrder.payment_method" class="form-control" asp-items="ViewBag.payment_method"></select>
                <span asp-validation-for="SaleOrder.payment_method" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="SaleOrder.date_created" class="control-label"></label>
                <input asp-for="SaleOrder.date_created" class="form-control" />
                <span asp-validation-for="SaleOrder.date_created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SaleOrder.state" class="control-label"></label>
                <input asp-for="SaleOrder.state" class="form-control" />
                <span asp-validation-for="SaleOrder.state" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-9">
        <h4>Line Items</h4>
    </div>
    <div class="col-3 text-right">
        <button type="button" id="addLineItem" class="btn btn-primary">Add Line Item</button>
    </div>
</div>
<br>
<div class="row">
    <table class="table table-bordered border-dark">
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody id="lineItemsBody">
            @for (int i = 0; i < Model.SaleItems.Count; i++)
            {
                <tr>
                    <td>
                        @Html.DropDownListFor(model => model.SaleItems[i].product_id, (SelectList)ViewData["product_id"], "Select a Product", new { @class = "form-control" })
                        <span asp-validation-for="SaleItems[i].product_id" class="text-danger"></span>
                    </td>
                    <td>
                        <input asp-for="SaleItems[i].quantity" class="form-control" />
                        <span asp-validation-for="SaleItems[i].quantity" class="text-danger"></span>
                    </td>
                    <td>
                        <input asp-for="SaleItems[i].price" class="form-control" />
                        <span asp-validation-for="SaleItems[i].price" class="text-danger"></span>
                    </td>
                    <td>
                        <button type="button" class="btn btn-danger removeLineItem">Remove</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
*@

@section Scripts {
    <script>
        $(document).ready(function () {
            var index = @Model.SaleItems.Count;

            $('#addLineItem').click(function () {
                var newRow = '<tr>' +
                    '<td><select class="form-control" name="SaleItems[' + index + '].product_id"><option value="">Select a Product</option></select></td>' +
                    '<td><input class="form-control" name="SaleItems[' + index + '].quantity" /></td>' +
                    '<td><input class="form-control" name="SaleItems[' + index + '].price" /></td>' +
                    '<td><button type="button" class="btn btn-danger removeLineItem">Remove</button></td>' +
                    '</tr>';

                $('#lineItemsBody').append(newRow);

                var select = $('select[name="SaleItems[' + index + '].product_id"]');
                $.get('@Url.Action("GetProducts", "Products")', function (data) {
                    select.empty();
                    $.each(data, function (index, item) {
                        select.append($('<option></option>').val(item.value).text(item.text));
                    });
                });

                index++;
            });

            $(document).on('click', '.removeLineItem', function () {
                $(this).closest('tr').remove();
            });
        });
    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

SLG/Views/Sale_Order/Index.cshtml
@model IEnumerable<Sale_Order>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.total_amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.date_created)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.state)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.customer)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
            <tr >
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.total_amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.date_created)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.state)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.customer.customer_name)
                </td>
                
                <td>
                    <a asp-action="Edit" asp-route-id="@item.sale_id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.sale_id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.sale_id">Delete</a>
                        @if (item.state == "Quotation" || item.state == "Quotation Sent")
                        {
                            <p>| <a asp-action="ConfirmSaleOrder" asp-route-id="@item.sale_id">Confirm</a></p>
                        }
                        @if (item.state == "Sale Order")
                        {
                        <p>| <a asp-action="CreateInvoice" asp-route-id="@item.sale_id">Create Invoice</a></p>
                        }

                </td>
            </tr>
    }
        </tbody>
</table>